title : pokerG
tagline: "Man is a by deposed king, otherwise wouldn't have lost because his throne and sad"
author :
  name : pokerG Hao
  email : pokerfacehlg@gmail.com
  github : pokerG
  twitter : username
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
